export const SOCKET_EVENTS = {
  allLog: "allLog",
  allReady: "allReady",
  condition: "condition",
  createLobby: "createLobby",
  deleteLobby: "deleteLobby",
  disconnect: "disconnect",
  endHod: "endHod",
  getAllPlayers: "getAllPlayers",
  getDoorCardByPlayer: "getDoorCardByPlayer",
  getLobbys: "getLobbys",
  goTo: "goTo",
  helpAnswer: "helpAnswer",
  helpAsk: "helpAsk",
  pas: "pas",
  plusLog: "plusLog",
  refreshGame: "refreshGame",
  refreshRooms: "refreshRooms",
  roomIn: "roomIn",
  roomOut: "roomOut",
  sbrosCard: "sbrosCard",
  sbrosEquip: "sbrosEquip",
  sellCard: "sellCard",
  setReady: "setReady",
  setSex: "setSex",
  smivka: "smivka",
  statusCreate: "statusCreate",
  statusDelete: "statusDelete",
  statusLobby: "statusLobby",
  statusPlayer: "statusPlayer",
  statusRoomIn: "statusRoomIn",
  toHome: "toHome",
  useCard: "useCard",
  useCardMesto: "useCardMesto",
} as const;

export type SocketEvent = typeof SOCKET_EVENTS[keyof typeof SOCKET_EVENTS];

